### PR TITLE
Support for Helldivers 2

### PR DESCRIPTION
**Pull request by Iaotle**
some strategem codes are still missing

### CODE REVIEW

**Comment by Wupb** [comment]
This breaks support Helldivers 1 as well as introduces some hardcoded values. However, I can add support for Helldivers 2 alongside with 1. Also, is it necessary to hold down the directional keys for a set amount of time, as opposed to simply sending the keystroke?

**Comment by Iaotle** [comment]
Only way it worked for me in H2. I'm no AHK expert. And yes, this breaks og helldivers (though how could you not if the strategems are different?)

**Comment by Wupb** [comment]
10a02ebcdc8981aab461a374aa5d457dcc1bb7d2 Should work for 2.

**Comment by Iaotle** [comment]
@Wupb I think the devs changed somehting, I haven't been able to get it working since a yesterday.

**Pull request closed without merging**
